name: nalia_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  rxdart: ^0.25.0
  dio: ^3.0.10
  get: ^3.24.0
  get_storage: ^1.4.0

  # PASS LOGIN
  webview_flutter: ^1.0.7

  cached_network_image: ^2.5.0

  location: ^3.1.0

  flutter_icons: ^1.1.0

  faker: ^1.3.0
  age: ^0.0.1

  # Scroll to a specific item in list view.
  scrollable_positioned_list: ^0.1.8

  image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: image_picker_workaround
      path: packages/image_picker/image_picker

  flutter_image_compress: ^0.7.0

  audio_wave:
    path: packages/audio_wave

  text_scroller:
    path: packages/text_scroller

  icon_animator:
    path: packages/icon_animator

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
