name: nalia_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  rxdart: ^0.25.0
  dio: ^3.0.10
  get: ^3.24.0
  get_storage: ^1.4.0

  # PASS LOGIN
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
